# Generated by Django 5.2 on 2025-05-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0004_registereduser_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='phone_number',
            new_name='contact_number',
        ),
    ]
