# Generated by Django 5.2 on 2025-05-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0005_rename_phone_number_registereduser_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
