# Generated by Django 5.2 on 2025-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
