# Generated by Django 5.2 on 2025-05-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0007_registereduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='admin', max_length=10),
        ),
    ]
