# Generated by Django 5.1.7 on 2025-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0008_alter_registereduser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('stocks', models.IntegerField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ("Kid's", "Kid's")], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='uploadImg/')),
            ],
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
