# Generated by Django 5.1.7 on 2025-05-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0009_products_alter_registereduser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
