# Generated by Django 5.2 on 2025-05-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0010_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='image',
            field=models.ImageField(blank=True, upload_to='UsersImg'),
        ),
    ]
