# Generated by Django 5.1.7 on 2025-05-10 17:23

import Nike_Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0011_registereduser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to=Nike_Store.models.path_unique_image_name),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to=Nike_Store.models.path_unique_image_name),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to=Nike_Store.models.path_unique_image_name),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, upload_to=Nike_Store.models.path_unique_image_name),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, upload_to=Nike_Store.models.path_unique_image_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=Nike_Store.models.path_unique_image_name),
        ),
    ]
