# Generated by Django 5.1.7 on 2025-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0012_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='shoes_categories',
            field=models.CharField(blank=True, choices=[('Lifestyle', 'Lifestyle'), ('Jordan', 'Jordan'), ('Running', 'Running'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Gym and Training', 'Gym and Training')], max_length=50),
        ),
    ]
