# Generated by Django 5.2 on 2025-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0013_rename_category_product_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=150)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_gender', models.CharField(blank=True, max_length=10)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('product_quantity', models.IntegerField(blank=True)),
            ],
        ),
    ]
