# Generated by Django 5.2 on 2025-05-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0014_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id_fk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
