# Generated by Django 5.2 on 2025-05-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0015_cart_product_id_fk_alter_cart_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='cartImages/'),
        ),
    ]
