# Generated by Django 5.2 on 2025-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0016_cart_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
