# Generated by Django 5.2 on 2025-05-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0017_cart_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
