# Generated by Django 5.1.7 on 2025-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0018_alter_cart_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('Firstname', models.CharField(blank=True, max_length=50)),
                ('Middlename', models.CharField(blank=True, max_length=50)),
                ('Lastname', models.CharField(blank=True, max_length=50)),
                ('Contact_Number', models.IntegerField(blank=True)),
                ('Address', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('shipped', 'shipped'), ('Complete', 'Complete')], default='Pending', max_length=20)),
                ('member', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
