# Generated by Django 5.1.7 on 2025-05-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0019_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='ShippingAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Firstname',
            new_name='item_category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Middlename',
        ),
        migrations.AddField(
            model_name='order',
            name='Fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='item_ID',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='item_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='item_Price',
            field=models.DecimalField(blank=True, decimal_places=2, default=2499, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='item_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='item_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='item_quantity',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='item_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='item_totalprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=35000, max_digits=20),
            preserve_default=False,
        ),
    ]
