# Generated by Django 5.1.7 on 2025-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0020_rename_address_order_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment_Method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Gcash', 'Gcash'), ('Cash On Delivery', 'Cash On Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Shipped', 'Shipped'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
