# Generated by Django 5.1.7 on 2025-05-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0022_order_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_payments',
            field=models.DecimalField(blank=True, decimal_places=2, default=34257, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
