# Generated by Django 5.1.7 on 2025-05-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0023_order_total_payments_alter_order_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
