# Generated by Django 5.1.7 on 2025-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0024_alter_order_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_createdAt',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
