# Generated by Django 5.1.7 on 2025-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0025_order_order_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_id',
            field=models.IntegerField(blank=True, default=23),
            preserve_default=False,
        ),
    ]
