# Generated by Django 5.1.7 on 2025-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nike_Store', '0027_order_barangay_order_city_order_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ShippingAddress',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
